"""Test backward compatibility: new and old network systems must generate isomorphic graphs

This test suite validates that the new rule-based network system produces
compute graphs that are isomorphic to those generated by the old imperative system.
This ensures we haven't broken anything during the migration.

Based on the patterns in roadmap.md.
"""

import pytest
import json5
from pathlib import Path
from collections import Counter

import biocomp.recipe_old as reco
import biocomp.recipe_new as recn
import biocomp.network_new as netn
import biocomp.biorules as br
from biocomp.graphengine import apply_rule_sequence, graphs_are_isomorphic
from biocomp.library import load_lib, LibraryContext


# ============================================================================
# Fixtures
# ============================================================================

@pytest.fixture(scope="module")
def lib():
    """Load parts library once for all tests"""
    return load_lib()


@pytest.fixture(scope="module")
def recipe_paths():
    """Get all test recipe paths"""
    test_recipe_path = Path("biocomp/tests/networks/old_recipes")
    paths = sorted(test_recipe_path.glob("*.json5"))
    return paths


@pytest.fixture(scope="module")
def recipes_data(recipe_paths, lib):
    """Load and parse all recipes, returning (path, dict, parsed_recipe) tuples

    Filters out recipes that fail to parse.
    """
    results = []
    failed = []

    for path in recipe_paths:
        try:
            recipe_dict = json5.load(open(path))
            recipe_obj = recn.dict_to_recipe(recipe_dict)
            results.append((path, recipe_dict, recipe_obj))
        except Exception as e:
            failed.append((path.name, str(e)))

    if failed:
        print(f"\nWarning: {len(failed)} recipes failed to parse:")
        for name, error in failed:
            print(f"  - {name}: {error}")

    return results


# ============================================================================
# Helper Functions (from roadmap.md)
# ============================================================================

def build_old_network(recipe_path, lib):
    """Build network using old imperative system"""
    def error_handler(msg):
        print(f"Old system error: {msg}")
        return False

    old_net = reco.network_from_recipe(
        recipe_path, lib, inverse="all", error_handler=error_handler
    )[0]
    old_net.build()
    return old_net


def build_new_network_cdg(recipe, lib):
    """Build CDG using new declarative system"""
    new_net = netn.Network(cotx=recipe.content)
    cdg = netn.build_central_dogma_graph_direct(new_net, lib, dual=True)
    return cdg


def build_new_network_compg(recipe, lib):
    """Build compute graph using new declarative system with rules"""
    cdg = build_new_network_cdg(recipe, lib)
    compg = apply_rule_sequence(br.ALL_RULES, cdg)[0]
    return compg


def old_network_to_graphstate(old_net):
    """Convert old network's compute graph to GraphState"""
    return netn.old_network_compg_to_graphstate(old_net)


# ============================================================================
# Basic Sanity Tests
# ============================================================================

def test_recipes_loaded(recipes_data):
    """Sanity check: ensure we loaded some recipes"""
    assert len(recipes_data) > 0, "No recipes were loaded"
    print(f"\nLoaded {len(recipes_data)} valid recipes")


def test_old_system_still_works(recipe_paths, lib):
    """Sanity check: old system can still build networks"""
    with LibraryContext.with_library(lib):
        for path in recipe_paths[:3]:  # Test first 3
            try:
                old_net = build_old_network(path, lib)
                assert old_net.is_built()
                assert old_net.compute_graph is not None
            except Exception as e:
                pytest.fail(f"Old system failed on {path.name}: {e}")


def test_new_system_builds_cdg(recipes_data, lib):
    """Sanity check: new system can build CDGs"""
    with LibraryContext.with_library(lib):
        for path, recipe_dict, recipe in recipes_data[:3]:  # Test first 3
            try:
                cdg = build_new_network_cdg(recipe, lib)
                assert len(cdg.nodes) > 0
                assert len(cdg.edges) > 0
            except Exception as e:
                pytest.fail(f"New CDG build failed on {path.name}: {e}")


def test_new_system_applies_rules(recipes_data, lib):
    """Sanity check: rules can be applied to CDGs"""
    with LibraryContext.with_library(lib):
        for path, recipe_dict, recipe in recipes_data[:3]:  # Test first 3
            try:
                compg = build_new_network_compg(recipe, lib)
                assert compg is not None
                assert len(compg.nodes) > 0
            except Exception as e:
                pytest.fail(f"Rule application failed on {path.name}: {e}")


# ============================================================================
# Structure Equivalence Tests
# ============================================================================

def test_node_count_equivalence(recipes_data, lib):
    """Test that old and new produce same number of nodes"""
    failed = []

    with LibraryContext.with_library(lib):
        for path, recipe_dict, recipe in recipes_data:
            try:
                old_net = build_old_network(path, lib)
                new_compg = build_new_network_compg(recipe, lib)
                old_compg = old_network_to_graphstate(old_net)

                if len(new_compg.nodes) != len(old_compg.nodes):
                    failed.append({
                        'name': path.name,
                        'new_count': len(new_compg.nodes),
                        'old_count': len(old_compg.nodes),
                    })
            except Exception as e:
                failed.append({
                    'name': path.name,
                    'error': str(e),
                })

    if failed:
        print(f"\n❌ Node count mismatches for {len(failed)} recipes:")
        for item in failed:
            if 'error' in item:
                print(f"  - {item['name']}: ERROR - {item['error']}")
            else:
                print(f"  - {item['name']}: new={item['new_count']}, old={item['old_count']}")
        pytest.fail(f"Node count equivalence failed for {len(failed)}/{len(recipes_data)} recipes")


def test_edge_count_equivalence(recipes_data, lib):
    """Test that old and new produce same number of edges"""
    failed = []

    with LibraryContext.with_library(lib):
        for path, recipe_dict, recipe in recipes_data:
            try:
                old_net = build_old_network(path, lib)
                new_compg = build_new_network_compg(recipe, lib)
                old_compg = old_network_to_graphstate(old_net)

                if len(new_compg.edges) != len(old_compg.edges):
                    failed.append({
                        'name': path.name,
                        'new_count': len(new_compg.edges),
                        'old_count': len(old_compg.edges),
                    })
            except Exception as e:
                failed.append({
                    'name': path.name,
                    'error': str(e),
                })

    if failed:
        print(f"\n❌ Edge count mismatches for {len(failed)} recipes:")
        for item in failed:
            if 'error' in item:
                print(f"  - {item['name']}: ERROR - {item['error']}")
            else:
                print(f"  - {item['name']}: new={item['new_count']}, old={item['old_count']}")
        pytest.fail(f"Edge count equivalence failed for {len(failed)}/{len(recipes_data)} recipes")


def test_node_type_distribution(recipes_data, lib):
    """Test that node type distributions match"""
    failed = []

    with LibraryContext.with_library(lib):
        for path, recipe_dict, recipe in recipes_data:
            try:
                old_net = build_old_network(path, lib)
                new_compg = build_new_network_compg(recipe, lib)
                old_compg = old_network_to_graphstate(old_net)

                new_types = Counter(n.node_type for n in new_compg.nodes.values())
                old_types = Counter(n.node_type for n in old_compg.nodes.values())

                if new_types != old_types:
                    failed.append({
                        'name': path.name,
                        'new_types': dict(new_types),
                        'old_types': dict(old_types),
                    })
            except Exception as e:
                failed.append({
                    'name': path.name,
                    'error': str(e),
                })

    if failed:
        print(f"\n❌ Node type distribution mismatches for {len(failed)} recipes:")
        for item in failed:
            if 'error' in item:
                print(f"  - {item['name']}: ERROR - {item['error']}")
            else:
                print(f"  - {item['name']}:")
                print(f"      New: {item['new_types']}")
                print(f"      Old: {item['old_types']}")
        pytest.fail(f"Node type distribution failed for {len(failed)}/{len(recipes_data)} recipes")


# ============================================================================
# Graph Isomorphism Test (The Main Event)
# ============================================================================

def test_graph_isomorphism_all_recipes(recipes_data, lib):
    """Test that new and old systems produce isomorphic graphs for all recipes

    This is the comprehensive test based on roadmap.md that checks if the
    graphs are structurally equivalent (isomorphic).
    """
    passed = []
    failed = []
    errors = []

    with LibraryContext.with_library(lib):
        for path, recipe_dict, recipe in recipes_data:
            recipe_name = path.name

            try:
                # Build both networks (from roadmap.md)
                old_net = build_old_network(path, lib)
                new_compg = build_new_network_compg(recipe, lib)
                old_compg = old_network_to_graphstate(old_net)

                # Test isomorphism (from roadmap.md)
                iso = graphs_are_isomorphic(
                    new_compg,
                    old_compg,
                    unordered_outgoing_types={'aggregation'},
                    unordered_incoming_types={'output', 'translation', 'transcription'},
                )

                if iso:
                    passed.append(recipe_name)
                else:
                    failed.append({
                        'name': recipe_name,
                        'nodes': f"new={len(new_compg.nodes)}, old={len(old_compg.nodes)}",
                        'edges': f"new={len(new_compg.edges)}, old={len(old_compg.edges)}",
                    })

            except Exception as e:
                errors.append({
                    'name': recipe_name,
                    'error': str(e),
                })

    # Report results
    total = len(recipes_data)
    passed_count = len(passed)
    failed_count = len(failed)
    error_count = len(errors)
    success_rate = (passed_count / total * 100) if total > 0 else 0

    print(f"\n{'='*80}")
    print(f"GRAPH ISOMORPHISM TEST RESULTS")
    print(f"{'='*80}")
    print(f"Total recipes:  {total}")
    print(f"✅ Passed:      {passed_count} ({success_rate:.1f}%)")
    print(f"❌ Failed:      {failed_count}")
    print(f"⚠️  Errors:      {error_count}")
    print(f"{'='*80}")

    if failed:
        print(f"\n❌ Failed isomorphism checks:")
        for item in failed:
            print(f"  - {item['name']}")
            print(f"      {item['nodes']}, {item['edges']}")

    if errors:
        print(f"\n⚠️  Errors during processing:")
        for item in errors:
            print(f"  - {item['name']}")
            print(f"      {item['error']}")

    # Collect all problematic recipes for reporting
    problematic = failed + errors

    if problematic:
        problem_names = [item['name'] for item in problematic]
        print(f"\n{'='*80}")
        print(f"PROBLEMATIC RECIPES ({len(problem_names)}):")
        print(f"{'='*80}")
        for name in sorted(problem_names):
            print(f"  - {name}")
        print(f"{'='*80}")

        # Create detailed failure message
        msg = f"\nGraph isomorphism test failed for {len(problematic)}/{total} recipes.\n"
        msg += f"Success rate: {success_rate:.1f}%\n\n"
        msg += "Problematic recipes:\n"
        for item in problematic:
            if 'error' in item:
                msg += f"  ❌ {item['name']}: {item['error']}\n"
            else:
                msg += f"  ❌ {item['name']}: Graphs are not isomorphic\n"

        pytest.fail(msg)

    print(f"\n✅ All {total} recipes produce isomorphic graphs!")


# ============================================================================
# Individual Recipe Debugging Tests
# ============================================================================

@pytest.mark.parametrize("recipe_idx", [0, 1, 2])
def test_first_few_recipes_detailed(recipes_data, lib, recipe_idx):
    """Detailed test for first few recipes to help with debugging"""
    if recipe_idx >= len(recipes_data):
        pytest.skip(f"Recipe index {recipe_idx} not available")

    path, recipe_dict, recipe = recipes_data[recipe_idx]

    print(f"\n{'='*80}")
    print(f"Testing: {path.name}")
    print(f"{'='*80}")

    with LibraryContext.with_library(lib):
        # Build old network
        old_net = build_old_network(path, lib)
        print(f"Old network built: {old_net.name}")
        print(f"  TUs: {len(old_net.transcription_units)}")
        print(f"  Aggregations: {len(old_net.aggregations)}")

        # Build new CDG
        cdg = build_new_network_cdg(recipe, lib)
        print(f"\nNew CDG built:")
        print(f"  Nodes: {len(cdg.nodes)}")
        print(f"  Edges: {len(cdg.edges)}")

        # Apply rules
        compg = apply_rule_sequence(br.ALL_RULES, cdg)[0]
        print(f"\nAfter applying rules:")
        print(f"  Nodes: {len(compg.nodes)}")
        print(f"  Edges: {len(compg.edges)}")

        # Convert old
        old_compg = old_network_to_graphstate(old_net)
        print(f"\nOld compute graph:")
        print(f"  Nodes: {len(old_compg.nodes)}")
        print(f"  Edges: {len(old_compg.edges)}")

        # Check isomorphism
        iso = graphs_are_isomorphic(
            compg,
            old_compg,
            unordered_outgoing_types={'aggregation'},
            unordered_incoming_types={'output', 'translation', 'transcription'},
        )

        print(f"\nIsomorphic: {iso}")

        if not iso:
            # Show node type distribution
            new_types = Counter(n.node_type for n in compg.nodes.values())
            old_types = Counter(n.node_type for n in old_compg.nodes.values())
            print(f"\nNode type distribution:")
            print(f"  New: {dict(new_types)}")
            print(f"  Old: {dict(old_types)}")

        assert iso, f"Graphs are not isomorphic for {path.name}"
