node_functions:

  transcription:
    fname: transform_nn
    kwargs:
      transform_name: tc
      quantization_names:
      - hEF1a
      outer_wsize: 64
      outer_depth: 4
      inner_wsize: 64
      inner_depth: 3
      inner_outsize: 8
      rate_dim: 1
      is_inverse: false
      inner_activation_name: leaky_relu
      outer_activation_name: sigmoid
    module: biocomp.nodes

  translation:
    fname: transform_nn
    kwargs:
      transform_name: tl
      quantization_names:
      - 00_empty_tc
      - 1w_uORF
      - 1x_uORF
      - 2x_uORF
      - 3x_uORF
      - 4x_uORF
      - 5x_uORF
      - 6x_uORF
      - 8x_uORF
      - 9x_uORF
      - 10x_uORF
      - 11x_uORF
      - 12x_uORF
      outer_wsize: 64
      outer_depth: 4
      inner_wsize: 64
      inner_depth: 3
      inner_outsize: 8
      rate_dim: 1
      is_inverse: false
      inner_activation_name: leaky_relu
      outer_activation_name: sigmoid
    module: biocomp.nodes

  inv_transcription:
    fname: transform_nn
    kwargs:
      transform_name: tc
      quantization_names: ${transcription.kwargs.quantization_names}
      outer_wsize: 64
      outer_depth: 4
      inner_wsize: 64
      inner_depth: 3
      inner_outsize: 8
      rate_dim: 1
      is_inverse: true
      inner_activation_name: leaky_relu
      outer_activation_name: sigmoid
    module: biocomp.nodes

  inv_translation:
    fname: transform_nn
    kwargs:
      transform_name: tl
      quantization_names: ${translation.kwargs.quantization_names}
      outer_wsize: 64
      outer_depth: 4
      inner_wsize: 64
      inner_depth: 3
      inner_outsize: 8
      rate_dim: 1
      is_inverse: true
      inner_activation_name: leaky_relu
      outer_activation_name: sigmoid
    module: biocomp.nodes

  sequestron_ERN:
    fname: sequestron_ERN
    kwargs:
      affinity_names:
      - ERN::CasE#CasE_rec
      - ERN::Csy4#Csy4_rec
      - ERN::PgU#PgU_rec
      affinity_dim: 1
      wsize: 128
      depth: 4
      out_dim: 1
      subtype: 5p
      inner_activation_name: leaky_relu
      outer_activation_name: sigmoid
    module: biocomp.nodes

  source:
    fname: source
    kwargs: {}
    module: biocomp.nodes

  inv_source:
    fname: inv_source
    kwargs: {}
    module: biocomp.nodes

  bias:
    fname: bias
    kwargs:
      shape:
      - 1
    module: biocomp.nodes

  numeric:
    fname: bias
    kwargs:
      shape:
      - 1
    module: biocomp.nodes

  aggregation:
    fname: aggregation
    kwargs:
      stack: null
    module: biocomp.nodes

  inv_aggregation:
    fname: inv_aggregation
    kwargs: {}
    module: biocomp.nodes

  output:
    fname: grouped_output
    kwargs:
      wsize: 64
      depth: 4
      inner_activation_name: leaky_relu
      outer_activation_name: sigmoid
    module: biocomp.nodes

  deadend:
    fname: single_passthrough
    kwargs: {}
    module: biocomp.nodes

extra: null

